version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      python-runtime:
        patterns:
          - "*"
    ignore:
      - dependency-name: "redis"
        versions:
          - ">= 6.0.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
